# Generated by Django 3.1.2 on 2020-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_build_func', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelingfunction',
            options={'verbose_name': 'График функции', 'verbose_name_plural': 'Графики функций'},
        ),
        migrations.AlterField(
            model_name='modelingfunction',
            name='date_treatment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обработки'),
        ),
        migrations.AlterField(
            model_name='modelingfunction',
            name='graphic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='График'),
        ),
    ]
